---
apiVersion: v1
kind: Service
metadata:
  name: ran-o1-sim-du
  namespace: ran-o1-sim
  labels:
    app: ran-o1-sim-du
spec:
  selector:
    app: ran-o1-sim-du
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
  - name: netconf
    port: 830
    targetPort: 830
    protocol: TCP
  type: ClusterIP
