apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdnr.fullname" . }}-certs-config
  labels:
    {{- include "sdnr.labels" . | nindent 4 }}
data:
  certs.properties: |-
    {{- .Files.Get "files/certs.properties" | nindent 4 }}
