apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdnr.fullname" . }}-logging-config
  labels:
    {{- include "sdnr.labels" . | nindent 4 }}
data:
  org.ops4j.pax.logging.cfg: |-
    {{- .Files.Get "files/org.ops4j.pax.logging.cfg" | nindent 4 }}
