apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdnr.fullname" . }}-keys1
  labels:
    {{- include "sdnr.labels" . | nindent 4 }}
type: Opaque
data:
  keys1.zip: {{ .Files.Get "files/keys1.zip" | b64enc | quote }}
