apiVersion: v1
kind: Service
metadata:
  name: persistence
  namespace: ridenext-nonrt
  labels:
    app: persistence
spec:
  selector:
    app: persistence
  ports:
  - name: http
    port: 9200
    targetPort: 9200
