apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdnr.fullname" . }}-devicemanager-config
  labels:
    {{- include "sdnr.labels" . | nindent 4 }}
data:
  devicemanager.properties: |-
    {{- .Files.Get "files/devicemanager.properties" | nindent 4 }}
