apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdnr.fullname" . }}-mountpoint-config
  labels:
    {{- include "sdnr.labels" . | nindent 4 }}
data:
  mountpoint-registrar.properties: |-
    {{- .Files.Get "files/mountpoint-registrar.properties" | nindent 4 }}
