apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdnr.fullname" . }}-oauth-config
  labels:
    {{- include "sdnr.labels" . | nindent 4 }}
data:
  oauth-provider.config.json: |-
    {{- .Files.Get "files/oauth-provider.config.json" | nindent 4 }}
