apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdnr.fullname" . }}-keys0
  labels:
    {{- include "sdnr.labels" . | nindent 4 }}
type: Opaque
data:
  keys0.zip: {{ .Files.Get "files/keys0.zip" | b64enc | quote }}
