apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rappmanager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rappmanager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rappmanager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rappmanager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        {{- toYaml .Values.env | nindent 8 }}
        #{{- if .Values.livenessProbe }}
        #livenessProbe:
        #  {{- toYaml .Values.livenessProbe | nindent 10 }}
        #{{- end }}
        #{{- if .Values.readinessProbe }}
        #readinessProbe:
        #  {{- toYaml .Values.readinessProbe | nindent 10 }}
        #{{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: csar-storage
          mountPath: {{ .Values.persistence.mountPath }}
        {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: csar-storage
        persistentVolumeClaim:
          claimName: {{ include "rappmanager.fullname" . }}-pvc
      {{- end }}
