#  ============LICENSE_START===============================================
#  Copyright (C) 2020-2023 Nordix Foundation. All rights reserved.
#  Copyright (C) 2023 OpenInfra Foundation Europe. All rights reserved.
#  ========================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ============LICENSE_END=================================================
#


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-producer-pm-json2influx
  namespace: ridenext-nonrt
  labels:
    app: kafka-producer-pm-json2influx

spec:
  replicas: 1
  serviceName: kafka-producer-pm-json2influx
  selector:
    matchLabels:
      app: kafka-producer-pm-json2influx
  template:
    metadata:
      labels:
        app: kafka-producer-pm-json2influx

    spec:
      containers:
      - name: kafka-producer-pm-json2influx
        image: {{ .Values.kafkaproducerpmjson2influx.image.repository }}:{{ .Values.kafkaproducerpmjson2influx.image.tag }}
        imagePullPolicy: {{ .Values.kafkaproducerpmjson2influx.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
        env:
        - name: E1
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KP
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        - name: KAFKA_SERVER
          value: kafka-1-kafka-bootstrap.ridenext-nonrt:9092
        - name: APP_KAFKA_BOOTSTRAP_SERVERS
          value: kafka-1-kafka-bootstrap.ridenext-nonrt:9092
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka-1-kafka-bootstrap.ridenext-nonrt:9092
        - name: USE_OAUTH_TOKEN
          value: "false"
        - name: APP_INFLUX_URL
          value: http://influxdb2.ridenext-nonrt:8086
        - name: APP_ICS_BASE_URL
          value: http://informationservice.ridenext-nonrt:8083
        - name: ICS
          value: informationservice.ridenext-nonrt:8083
        - name: SELF
          value: "$(E1).kafka-producer-pm-json2influx.ridenext-nonrt:80"
        - name: FILESTORE_USER
          value: admin
        - name: FILESTORE_PWD
          value: adminadmin
        - name: FILESTORE_SERVER
          value: minio.ridenext-nonrt:9000
        # OAuth credentials disabled - using PLAINTEXT authentication
        # - name: CREDS_GRANT_TYPE
        #   value: client_credentials
        # - name: CREDS_CLIENT_SECRET
        #   value: {{ .Values.kafkaproducerpmjson2influx.clientsecret }}
        # - name: CREDS_CLIENT_ID
        #   value: kafka-producer-pm-json2influx
        # - name: AUTH_SERVICE_URL
        #   value: http://keycloak.ridenext-nonrt:8080/realms/nonrtric-realm/protocol/openid-connect/token
        volumeMounts:
        - mountPath: /application_configuration.json
          subPath: application_configuration.json
          name: kafka-producer-pm-json2influx-cm-config
        - mountPath: /opt/app/pmlog-service/config/application.yaml
          subPath: application.yaml
          name: kafka-producer-pm-json2influx-app-config
        - mountPath: /opt/app/pmlog-service/config/jobDefinition.json
          subPath: jobDefinition.json
          name: kafka-producer-pm-json2influx-app-config
      volumes:
      - configMap:
          defaultMode: 420
          name: kafka-producer-pm-json2influx-cm-config
        name: kafka-producer-pm-json2influx-cm-config
      - configMap:
          defaultMode: 420
          name: kafka-producer-pm-json2influx-app-config
        name: kafka-producer-pm-json2influx-app-config
