{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdnc-web.fullname" . }}-location-rules
  labels:
    {{- include "sdnc-web.labels" . | nindent 4 }}
data:
  location.rules: |
    # Identity/Auth related locations
    location ~ ^/(realms|admin|auth)/ {
        proxy_pass http://identity;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
{{- end }}
