apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualization-frontend
  namespace: ridenext-nonrt
  labels:
    app: visualization-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualization-frontend
  template:
    metadata:
      labels:
        app: visualization-frontend
    spec:
      containers:
      - name: frontend
        image: localhost:5000/visualization-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: visualization-frontend
  namespace: ridenext-nonrt
spec:
  selector:
    app: visualization-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31801
  type: NodePort
